/*
 * Project structure
 *
 * app/             — Every subfolder in the app directory is a route.
 * app/layout.tsx   — This is the root layout of the application
 * app/page.tsx     — This is the entry point of the application serving the component at "/"
 * app/globals.css  — This is the global stylesheet for the application
 * next.config.ts   — This is the configuration file for Next.js to load plugins and configure various aspects of the application.
 * tsconfig.json    — This is the configuration file for TypeScript to specify compiler options and project settings.
 * public/          — This is the directory for static assets like images.
 * package.json     — This file contains all the dependencies and scripts for the project.
 * .next/           — This is the build output directory generated by Next.js, containing the compiled application ready for deployment.
 */

export default function Home(): React.ReactElement {
  return (
    <div className='h-screen flex items-center justify-center'>
      <main>
        <h1 className='text-4xl text-brand'>Welcome to My SaaS App</h1>
      </main>
    </div>
  );
}
